language: java

jdk:
  - oraclejdk11

cache:
  directories:
    - .autoconf
    - $HOME/.m2

install: true

jobs:
  include:
    - stage: install-yasson
      script: mvn -U -C -Pstaging clean install
    - stage: run-jmh
      script:
        - cd yasson-jmh
        - mvn clean install
        - java -jar target/yasson-jmh.jar -t 1 -f 2
    - stage: tck-run
      script: bash tck.sh


